### ISSUE TITLE
Support SFC?

### ISSUE THREAD

**Issue by deathlynocturnal** [xiaoluoboding/vue-sfc-sandbox#5]
Does this package support Vue SFC? So syntax highlighting and validation in a single .vue file? Instead of the split panes?

**Comment by xiaoluoboding** [comment]
@dannysmc95 In the beginning, I create this repo that renders a single SFC file, I release it in version v0.1.3. [check this demo](https://codesandbox.io/s/vue-sfc-sandbox-318nu)

but the UI was different from the version latest

 after that, I changed to split panes style inspired with vueuse playground.
